qy/admin/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import Required, EqualTo, Length

class RegForm(Form):
    eno = StringField('工号', validators=[Required('必填项')])
    password = PasswordField('密码', validators=[Required('请输入密码'), Length(6, 24, '密码长度 6-24 位')])
    password2 = PasswordField('确认密码', validators=[EqualTo('password', '两次密码不匹配')])
    submit = SubmitField('确认并注册')

class LoginForm(Form):
    eno = StringField('工号', validators=[Required('必填项')])
    password = PasswordField('密码', validators=[Required('请输入密码')])
    submit = SubmitField('进入')

class CertiForm(Form):
    body = StringField('认证主体', validators=[Required('必填')])
    function = TextAreaField('机构职能', validators=[Required('必填')])
    description = TextAreaField('描述')
    website = StringField('官方网站')
    address = TextAreaField('地址', validators=[Required('必填')])
    phone = StringField('服务电话')
    agent_id = StringField('代理人（身份证号）', validators=[Required('必填')])
    input = SubmitField('录入')

class CateForm(Form):
    name = StringField('添加新类型', validators=[Length(1, 32, '')])
    add = SubmitField('添加')

class AdminForm(Form):
    current_password = PasswordField('当前密码', validators=[Required('必填项')])
    new_password = PasswordField('新密码', validators=[Required('请输入新密码'), Length(6, 24, '密码长度 6-24 位')])
    new_password2 = PasswordField('确认新密码', validators=[EqualTo('new_password', '两次密码不匹配')])
    submit = SubmitField('确认更改')

qy/group/forms.py
from flask.ext.wtf import Form
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import Required, Length
from flask.ext.wtf.file import FileField, FileAllowed	#, FileRequired

class GroupForm(Form):
    name = StringField('小组名称', validators=[Required('必填项'), Length(1, 24, '名称最长24个字符')])
    icon = FileField('小组图标（建议尺寸120px*120px，只限jpg和png格式）', 
    	validators=[Required('小组图标必须有'), FileAllowed(['jpg', 'png'], '只限jpg和png格式')])
    intro = TextAreaField('介绍', validators=[Required('说说这个小组的事儿嘛')])
    save = SubmitField('确认')

class TopicForm(Form):
    title = StringField('标题', validators=[Required('标题必填'), Length(1, 128, '标题太长了 :(')])
    description = TextAreaField('详细描述（可不填）')
    post= SubmitField('发布')

class DiscuForm(Form):
    content = TextAreaField('也说点儿什么吧……', validators=[Required('还没填写呢')])
    reply = SubmitField('回复')

qy/main/forms.py
from flask.ext.wtf import Form
from wtforms import TextAreaField, SubmitField
from wtforms.validators import Required, Length

class TwitterForm(Form):
    content = TextAreaField('你在做什么/有什么想法？', validators=[Length(1, 140, '字数限定在 1-140 之间')])	#Required('输入你的想法'), 
    
    post = SubmitField('发布')

qy/__init__.py
from flask import Flask	#flask框架
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.migrate import Migrate  #还需pip install pymysql
from flask.ext.mail import Mail
from flask.ext.login import LoginManager    #登录管理
from flask.ext.moment import Moment

from config import config	#不同的配置，不同的运行模式

import os

bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
login_manager = LoginManager()
login_manager.session_protection = 'strong' #登录保护等级
login_manager.login_view = 'auth.login'
login_manager.login_message = '登录后方可访问'
login_manager.login_message_category = "alert-warning"
moment = Moment()

def create_app(config_name):
    '''工厂函数'''
    app = Flask(__name__)	#当前目录为根目录
    app.config.from_object(config[config_name])	#读取配置对象
    config[config_name].init_app(app)	#自己实现的staticmethod

    # 文件上传配置
    app.config['UPLOADS_DEFAULT_DEST'] = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'uploads/')    #F:\queyue\qy\uploads
    app.config['UPLOADS_DEFAULT_URL'] = 'http://127.0.0.1:5000/uploads/'

    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)  #注册一个蓝本
    from .auth import auth as auth_blueprint 
    app.register_blueprint(auth_blueprint)
    from .member import member as member_blueprint
    app.register_blueprint(member_blueprint, url_prefix='/member')
    from .resource import resource as resource_blueprint
    app.register_blueprint(resource_blueprint)
    from .event import event as event_blueprint
    app.register_blueprint(event_blueprint, url_prefix='/event')
    from .group import group as group_blueprint
    app.register_blueprint(group_blueprint, url_prefix='/group')
    from .institution import institution as institution_blueprint
    app.register_blueprint(institution_blueprint, url_prefix='/institution')
    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    return app

qy/admin/__init__.py
from flask import Blueprint, redirect, url_for, request, flash

admin = Blueprint('admin', __name__)

from . import views


def before_request():
    '''验证登录'''
    # print(request.endpoint)
    if request.endpoint=='admin.reg' or request.endpoint=='admin.login':
        pass
    else:
        if views.current_admin() is None:
            flash('需要登录', 'alert-warning')
            return redirect(url_for('admin.login'))

admin.before_request(before_request)

qy/admin/views.py
from . import admin
from .forms import RegForm, LoginForm, CertiForm, CateForm, AdminForm
from ..models import Admin, Certification, Category
from .. import db

from flask import render_template, request, flash, redirect, url_for, json, current_app, make_response
from itsdangerous import URLSafeSerializer

from threading import Thread
from datetime import datetime, timedelta

import requests as reqs

@admin.route('/')
def index():
    return redirect(url_for('.certi'))

# @admin.route('/', methods=['POST', 'GET'])
@admin.route('/certification', methods=['POST', 'GET'])
def certi():
    page = request.args.get('p', 1, type=int)
    cur_admin = current_admin()
    certi_form = CertiForm()
    if request.method=='POST' and certi_form.input.data and certi_form.validate_on_submit():
        certi = Certification.query.filter_by(body=certi_form.body.data).first()
        if certi is None:
            certi = Certification(body=certi_form.body.data, function=certi_form.function.data, 
                description=certi_form.description.data, website=certi_form.website.data, address=certi_form.address.data, 
                phone=certi_form.phone.data, agent_id=certi_form.agent_id.data, inputer_id=cur_admin.id)
            db.session.add(certi)
            flash('录入成功', 'alert-success')
            return redirect(url_for('.index'))
        else:
            flash('已存在的认证主体', 'alert-danger')
    pagination = Certification.query.order_by(Certification.certi_date.desc()).paginate(page, per_page=current_app.config['ITEMS_PER_PAGE'])
    certis = pagination.items
    return render_template('admin/certi.html', current_admin=cur_admin, certi_form=certi_form, certis=certis, pagination=pagination)

@admin.route('/delete-certi/<int:id>')
def delete_certi(id):
    try:
        certi = Certification.query.get_or_404(int(id))
        db.session.delete(certi)
        flash('删除成功', 'alert-success')
    except:
        flash('出错了，删除失败', 'alert-danger')
        pass
    return redirect(url_for('.certi'))

@admin.route('/extend/<cid>')
def extend(cid):
    try:
        certi = Certification.query.get_or_404(int(cid))
        certi.expiry_date = certi.expiry_date+timedelta(days=365)
        db.session.add(certi)
        flash('续期成功', 'alert-success')
        print('hello')
    except Exception as e:
        print(str(e))
        flash('续期失败……', 'alert-danger')
    return redirect(url_for('.certi'))

@admin.route('/category', methods=['POST', 'GET'])
def cate():
    cate_form = CateForm()
    if request.method=='POST' and cate_form.add.data and cate_form.validate_on_submit():
        if not (cate_form.name.data is None or cate_form.name.data==''):
            cate = Category.query.filter_by(name=cate_form.name.data).first()
            if cate is None:
                cate = Category(name=cate_form.name.data)
                db.session.add(cate)
                flash('添加成功', 'alert-success')
            else:
                flash('该类型已存在', 'alert-danger')
        else:
            flash('未输入类型名')
        tab_eq = 1
    cates = Category.query.all()
    return render_template('admin/cate.html', current_admin=current_admin(), cate_form=cate_form, cates=cates)

@admin.route('/misc', methods=['POST', 'GET'])
def misc():
    return render_template('admin/misc.html', current_admin=current_admin())

@admin.route('/settings', methods=['POST', 'GET'])
def settings():
    admin_form = AdminForm()
    if request.method=='POST' and admin_form.submit.data and admin_form.validate_on_submit():
        admin = current_admin()
        if admin.verify_password(admin_form.current_password.data):
            admin.password = admin_form.new_password.data
            db.session.add(admin)
            flash('修改成功', 'alert-success')
        else:
            flash('密码错误，修改失败', 'alert-danger')
    return render_template('admin/settings.html', current_admin=current_admin(), admin_form=admin_form)

@admin.route('/delete-category/<int:cid>')
def delete_category(cid):
    if cid is not None:
        try :
            cate = Category.query.get(int(cid))
        except:
            pass
        if cate is not None:
            db.session.delete(cate)
            flash('删除成功', 'alert-success')
    return redirect(url_for('.index', current_admin=current_admin(), tab_eq=1))

@admin.route('/reg', methods=['GET', 'POST'])
def reg():
    reg_form = RegForm()
    if request.method == 'POST' and reg_form.validate_on_submit():
        admin = Admin.query.filter_by(eno=reg_form.eno.data).first()
        if admin is None:
            admin = Admin(eno=reg_form.eno.data, password=reg_form.password.data)
            db.session.add(admin)
            flash('注册成功，可以登录了。', 'alert-success')
            return redirect(url_for('admin.login'))
        else:
            flash('该工号注册过了', 'alert-danger')

    return render_template('admin/reg.html', current_admin=current_admin(), form=reg_form)

@admin.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if request.method == 'POST' and login_form.validate_on_submit():
        admin = Admin.query.filter_by(eno=login_form.eno.data).first()
        if admin is not None:
            if admin.verify_password(login_form.password.data):
                flash('欢迎回来', 'alert-success')
                # “记住”登录状态
                resp = make_response(redirect(url_for('.index')))
                s = URLSafeSerializer(current_app.config['SECRET_KEY'])
                resp.set_cookie('admin-eno', s.dumps(admin.eno), expires=datetime.now()+timedelta(days=1))  # 24小时有效期
                return resp
            else:
                flash('密码错误', 'alert-danger')
        else:
            flash('不存在的账号', 'alert-danger')

    return render_template('admin/login.html', form=login_form)

@admin.route('/logout')
def logout():
    resp = make_response(redirect(url_for('.login')))
    resp.set_cookie('admin-eno', '', expires=0)
    flash('退出成功', 'alert-success')
    return resp

def current_admin():
    admin_eno = request.cookies.get('admin-eno')
    if admin_eno:
        s = URLSafeSerializer(current_app.config['SECRET_KEY'])
        eno = s.loads(admin_eno)
        return Admin.query.filter_by(eno=eno).first()
    return None

# def analyze_and_store(app_context, district_list, index, start_index, end_index, parent_id=None):
#     with app_context:
#         for d in district_list[index]:
#             id = d['id']
#             print(id)
#             name = d.get('name', None)
#             fullname = d['fullname']
#             py = d.get('pinyin', None)
#             pinyin = None
#             if py is not None:
#                 pinyin = ''
#                 for w in py:
#                     pinyin = pinyin + w.title()
#             longitude = d['location']['lat']
#             latitude = d['location']['lng']

#             district = District.query.filter_by(add_code=id).first()
#             if district is None:
#                 district = District(add_code=id, name=name, fullname=fullname, pinyin=pinyin, 
#                     longitude=longitude, latitude=latitude, parent_id=parent_id)
#             else:
#                 district.name = name
#                 district.fullname = fullname
#                 district.pinyin = pinyin
#                 district.longitude = longitude
#                 district.latitude = latitude
#                 district.parent_id = parent_id
#             db.session.add(district)

#             cidx = d.get('cidx', None)
#             if cidx is not None:
#                 analyze_and_store(app_context, district_list, index+1, cidx[0], cidx[1], parent_id=district.id)

# @admin.route('/update-district')
# def update_district():
#     # 获得WebService API返回的内容
#     app = current_app._get_current_object()
#     app_config = app.config
#     params = {'key': app_config['TCMAP_KEY']}
#     resp = reqs.get('http://apis.map.qq.com/ws/district/v1/list', params)
#     try:
#         content = resp.json()
#     except:
#         pass    #简化步骤，不处理
#     else:
#         # 下面开始分析和存储
#         if content['status']==0:
#             districts = content['result']   # three arrays
#             try:
#                 thr = Thread(target=analyze_and_store, args=[app.app_context(), districts, 0, 0, len(districts[0])-1])
#                 thr.start()
#             except:
#                 pass
#             else:
#                 flash('更新成功，最新的日期版本为 %r' % content['data_version'], 'alert-success')
#                 return redirect(url_for('admin.index'))
#     # 没成功时走这一步
#     flash('遇到了一些异常，更新失败。', 'alert-danger')
#     return redirect(url_for('admin.index'))

qy/event/__init__.py
from flask import Blueprint

event = Blueprint('event', __name__)

from . import views

qy/event/views.py
from . import event
from .. import db
from ..models import Event, User, Participate, Institution, Track

from flask import render_template, redirect, url_for, flash, request, current_app
from flask.ext.login import login_required, current_user

@event.route('/')	#, methods=['GET']
@login_required
def event_index():
    my_events = Event.query.join(Participate, Participate.event_id==Event.id).filter(Participate.user_id==current_user.id)\
        .order_by(Participate.partici_time.desc()).limit(7).all()
    my_instis = Institution.query.join(Track, Track.insti_id==Institution.id).filter(Track.user_id==current_user.id)\
        .order_by(Track.track_time.desc()).limit(6).all()
    new_events = Event.query.order_by(Event.new_time.desc()).limit(7).all()
    new_instis = Institution.query.order_by(Institution.enroll_date.desc()).limit(6).all()
    page = request.args.get('p', 1, type=int)
    pagination = current_user.my_events.order_by(Event.new_time.desc()).paginate(page, per_page=current_app.config['ITEMS_PER_PAGE'])
    my_eves = pagination.items
    return render_template('event/event.html', my_events=my_events, my_instis=my_instis, new_events=new_events, new_instis=new_instis, 
        pagination=pagination, events=my_eves)

@event.route('/<int:eid>')
def event_page(eid):
    event = Event.query.get_or_404(eid)
    entrants =  User.query.join(Participate, User.id==Participate.user_id).filter(Participate.event_id==event.id)\
    	.order_by(Participate.partici_time.desc()).all()
    return render_template('event/page.html', event=event, entrants=entrants)

@event.route('/<int:eid>/unpartici')
@login_required
def unpartici(eid):
    try:
        event = Event.query.get_or_404(int(eid))
        current_user.unpartici(event)
        flash('成功退出了活动 %s ' % event.name, 'alert-success')
    except Exception as e:
        flash('出了点错误，暂时无法退出该活动', 'alert-danger')
    return redirect(url_for('event.event_page', eid=eid))


@event.route('/<int:eid>/partici')
@login_required
def partici(eid):
    try:
        event = Event.query.get_or_404(int(eid))
        current_user.partici(event)
        flash('参加活动 %s 成功' % event.name, 'alert-success')
    except Exception as e:
        # flash(str(e), 'alert-danger')
        flash('出错了，暂时无法参加该活动', 'alert-danger')
    return redirect(url_for('event.event_page', eid=eid))

# @event.route('/map')
# def full_map():
#     lng = float(request.args.get('lng', 116.396574))
#     lat = float(request.args.get('lat', 39.992706))
#     return render_template('event/map.html', lng=lng, lat=lat)

qy/group/__init__.py
from flask import Blueprint

group = Blueprint('group', __name__)

from . import views

qy/institution/__init__.py
from flask import Blueprint, redirect, url_for, request, flash

institution = Blueprint('institution', __name__)

from . import views


def before_request():
    '''验证登录'''
    # print(request.endpoint)
    allowed_endpoints = ['institution.page', 'institution.index', 'institution.track', 'institution.untrack', 'institution.stuff']
    if request.endpoint in allowed_endpoints:
        pass
    else:
        # request.args.get('uurl')
        if views.current_insti() is None:
            flash('需要登录', 'alert-warning')
            return redirect(url_for('auth.signin'))

institution.before_request(before_request)

qy/main/__init__.py
from flask import Blueprint	#使用蓝本

main = Blueprint('main', __name__)	#实例化一个蓝本

from . import views, errors

qy/member/__init__.py
from flask import Blueprint

member = Blueprint('member', __name__)

from . import views, forms

qy/resource/__init__.py
from flask import Blueprint

resource = Blueprint('resource', __name__)

from . import views

qy/templates/institution/event.html
{% extends "bootstrap/base.html" %}

{% import 'bootstrap/wtf.html' as wtf %}
{% import "_macros.html" as macros %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang('zh-CN') }}
{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/bootstrap-datetimepicker.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/insti_panel.css') }}">
{% endblock %}

{% block title %}活动 - 机构后台{% endblock %}

{% block content %}
<!-- 问候信息 -->
<div>
	<h2 class="greet text-center">欢迎你，{{ insti.name or insti.uurl|upper }}</h2>
</div>

<!-- 消息栏 -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
	<div class="alert {{ category }} alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<span>{{ message }}</span>
	</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<!-- 功能板 -->
<div class="container">
	<!-- tabs -->
	<ul class="nav nav-tabs">
	   	<li> 
	   		<a href="{{ url_for('institution.notifi', uurl=insti.uurl) }}">通知</a>
	   	</li>
	   	<li class="active">
	   		<a href="{{ url_for('institution.event', uurl=insti.uurl) }}">活动管理</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.new_event', uurl=insti.uurl) }}">发布活动</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.profile', uurl=insti.uurl) }}">机构资料展示</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.settings', uurl=insti.uurl) }}">账户设置</a>
	   	</li>
	</ul>

	<!-- 活动 -->
	<div class="tab-pane">
		<div class="row">
			<div class="col-md-8">
				<!-- 活动列表 -->
				<table class="table table-hover">
					<caption>已发布的活动</caption>
					<thead>
						<tr>
							<th>序号</th>
							<th>活动名称</th>
							<th>活动状态</th>
							<th>编辑</th>
							<th>删除</th>
						</tr>
					</thead>
					<tbody>
						{% for event in events %}
						<tr>
							<!-- 序号 -->
							<td>{{ loop.index }}</td>
							<!-- 名称 -->
							<td>
								<a href="{{ url_for('event.event_page', eid=event.id) }}" target="_blank">{{ event.name }}</a>
							</td>
							<!-- 活动状态 -->
							<td>
								<span>{{ event.state()[1] }}</span>
							</td>
							<!-- 编辑 -->
							<td>
								<a href="{{ url_for('institution.edit_event', uurl=insti.uurl, eid=event.id) }}" target="_blank">
									<span class="glyphicon glyphicon-edit"></span>
								</a>
							</td>
							<!-- 删除 -->
							<td>
								<a href="" data-toggle="modal" data-target="#ask"><span class="glyphicon glyphicon-remove-circle"></span></a>
								<!-- 确认框 -->
								<div class="modal fade" id="ask" tabindex="-1" role="dialog" >
								   <div class="modal-dialog">
								   		<div class="modal-header">
		        							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		        								<span aria-hidden="true">&times;</span>
		        							</button>
		        							<h4>确认删除？</h4>
								      	</div>
								        <div class="modal-footer">
								        	<button type="button" class="btn btn-warning">
								        		<a href="{{ url_for('institution.delete_event', uurl=insti.uurl, id=event.id) }}">确认</a>
								        	</button>
								        	<button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
								        </div>
								    </div><!-- /.modal-content -->
								</div><!-- /.modal -->
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<!-- 分页器 -->
				{% if pagination %}
				<div>
					{{ macros.pagination_widget(pagination, 'institution.event', uurl=insti.uurl) }}
				</div>
				{% endif %}
			</div><!-- col-md-8 -->

			<div class="col-md-1"></div>

			<div class="col-md-3">
				<ul class="list-unstyled">
					<li><span>&gt;&nbsp;注意，已发布的活动只能修改描述和上传海报</span></li>
				</ul>
			</div>

		</div><!-- row -->
	</div><!-- tab-pane -->

</div>

{% endblock %}

qy/templates/institution/event_edit.html
{% extends "bootstrap/base.html" %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang('zh-CN') }}
{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/bootstrap-datetimepicker.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/insti_panel.css') }}">
{% endblock %}

{% block title %}更新活动 - 机构后台{% endblock %}

{% block content %}
<!-- 问候信息 -->
<div>
	<h2 class="greet text-center">欢迎你，{{ insti.name or insti.uurl|upper }}</h2>
</div>

<!-- 消息栏 -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
	<div class="alert {{ category }} alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<span>{{ message }}</span>
	</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<!-- 功能板 -->
<div class="container">
	<!-- tabs -->
	<ul class="nav nav-tabs">
	   	<li> 
	   		<a href="{{ url_for('institution.notifi', uurl=insti.uurl) }}">通知</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.event', uurl=insti.uurl) }}">活动管理</a>
	   	</li>
	   	<li class="active">
	   		<a href="">更新活动信息</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.new_event', uurl=insti.uurl) }}">发布活动</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.profile', uurl=insti.uurl) }}">机构资料展示</a>
	   	</li>
	   	<li>
	   		<a href="{{ url_for('institution.settings', uurl=insti.uurl) }}">账户设置</a>
	   	</li>
	</ul>

	<!-- 活动 -->
	<div class="tab-pane">
		<div class="row">
			<div class="col-md-8">
				<h2>更新活动描述/上传海报</h2>
				{{ wtf.quick_form(edit_form, button_map={'save': 'success pull-right'}) }}
			</div><!-- col-md-8 -->

			<div class="col-md-1"></div>

			<div class="col-md-3">
				<ul class="list-unstyled">
					<li>
						<span>&gt;&nbsp;</span><a href="{{ url_for('institution.event', uurl=insti.uurl) }}">回到活动管理页面</a>
					</li>
					<li>
						<span>&gt;&nbsp;</span>查看 <a href="{{ url_for('event.event_page', eid=event.id) }}" target="_blank">{{ event.name }}</a> 的主页
					</li>
				</ul>
			</div><!-- col-md-3 -->

		</div><!-- row -->
	</div><!-- tab-pane -->

</div>

{% endblock %}

qy/templates/institution/events.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}{{ insti.name }}的活动 | 雀跃{% endblock %}

{% block styles %}
{{ super() }}
<!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/index.css') }}"> -->
{% endblock %}

{% block page_content %}
<div class="container">
	<div class="row">
		<div class="col-md-2"><!-- 留白 --></div>
		
		<div id="mainbar" class="col-md-8">
			<h3 class="item">
				<span>{{ insti.name }}的活动</span>
				<span>&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;</span>
				<span>（共 {{ pagination.total }} 项）</span>
			</h3>

			<hr />

			<!-- 所有活动 -->
			{% for event in events %}
			<div>
				<h3>
					<a href="{{ url_for('event.event_page', eid=event.id) }}" target="_blank">{{ event.name }}</a>
				</h3>
				<p>
					<span>{{ event.detail[:240] }}</span>
					<a href="{{ url_for('event.event_page', eid=event.id) }}" target="_blank">阅读全部</a>
				</p>
				<dl class="dl-horizontal">
				  <dt>活动地点</dt>
				  <dd>{{ event.address }}</dd>
				  <dt>发布时间</dt>
				  <dd>{{ event.new_time }}</dd>
				  <dt>。</dt>
				  <dd><span class="{{ event.state()[0] }}">{{ event.state()[1] }}</span></dd>
				</dl>
			</div>
			<hr />
			{% endfor %}

			<!-- 分页器 -->
			{% if pagination %}
			<div>
				{{ macros.pagination_widget(pagination, 'institution.stuff', uurl=insti.uurl, obj='events') }}
			</div>
			{% endif %}
		</div>

		<div id='sidebar' class="col-md-2">
			<!--  -->
		</div>
	</div>
</div>
{% endblock %}